# Generated by Django 5.0.2 on 2025-07-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_purchase_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='payment_terms',
        ),
    ]
