# Generated by Django 5.0.2 on 2025-07-21 11:01

import vendors.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_alter_vendor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Customer image', null=True, upload_to=vendors.utils.upload_image_path),
        ),
    ]
