# Generated by Django 5.0.2 on 2025-07-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_tenantsettings_tenant_sett_tenant__e0b783_idx'),
        ('vendors', '0010_vendor_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('tenant', 'name')},
        ),
    ]
