# Generated by Django 5.0.2 on 2025-06-25 10:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_userproductpreference'),
        ('catalog', '0002_barcodes_alter_product_options_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('position_name', models.CharField(max_length=100)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_positions', to='core.currency')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='catalog.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'employee_positions',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('promoted', 'Promoted'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_careers', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_careers', to='core.currency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='accounts.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='hr.employeeposition')),
            ],
            options={
                'db_table': 'employee_careers',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit_share', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('asset_share', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.currency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.AddIndex(
            model_name='employeeposition',
            index=models.Index(fields=['tenant', 'is_active'], name='employee_po_tenant__7f64dd_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeposition',
            index=models.Index(fields=['department'], name='employee_po_departm_1e8f30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeposition',
            unique_together={('tenant', 'position_name')},
        ),
        migrations.AddIndex(
            model_name='employeecareer',
            index=models.Index(fields=['tenant', 'employee'], name='employee_ca_tenant__334d12_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecareer',
            index=models.Index(fields=['position'], name='employee_ca_positio_f5e78f_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecareer',
            index=models.Index(fields=['start_date'], name='employee_ca_start_d_f620f8_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecareer',
            index=models.Index(fields=['status'], name='employee_ca_status_78bd60_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['tenant', 'status'], name='members_tenant__aed80c_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['name'], name='members_name_09db5a_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['start_date'], name='members_start_d_09e3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['ownership_percentage'], name='members_ownersh_860a88_idx'),
        ),
    ]
