# Generated by Django 5.0.2 on 2025-07-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='asset_share',
        ),
        migrations.RemoveField(
            model_name='member',
            name='profit_share',
        ),
    ]
