# Generated by Django 5.0.2 on 2025-08-04 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_member_asset_share_remove_member_profit_share'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employeeposition',
            name='employee_po_departm_1e8f30_idx',
        ),
        migrations.RemoveField(
            model_name='employeeposition',
            name='department',
        ),
    ]
