# Generated by Django 5.0.2 on 2025-06-24 18:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_userproductpreference'),
        ('catalog', '0002_barcodes_alter_product_options_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('store', 'Store'), ('office', 'Office'), ('online', 'Online'), ('other', 'Other')], default='warehouse', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='core.address')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_locations', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_locations', to='accounts.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('count_number', models.CharField(max_length=50, unique=True)),
                ('count_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('total_items_counted', models.PositiveIntegerField(default=0)),
                ('variances_found', models.PositiveIntegerField(default=0)),
                ('completed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_counts', to=settings.AUTH_USER_MODEL)),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_counts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_counts', to='inventory.location')),
            ],
            options={
                'db_table': 'inventory_counts',
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('batch_number', models.CharField(max_length=50)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('supplier_batch_ref', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'product_batches',
            },
        ),
        migrations.CreateModel(
            name='InventoryCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('system_quantity', models.DecimalField(decimal_places=4, help_text='Quantity per system records', max_digits=15)),
                ('counted_quantity', models.DecimalField(decimal_places=4, help_text='Actual counted quantity', max_digits=15)),
                ('variance', models.DecimalField(decimal_places=4, help_text='Difference between counted and system quantity', max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_items', to='inventory.inventorycount')),
                ('counted_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_items', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_items', to='catalog.productvariant')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='count_items', to='inventory.productbatch')),
            ],
            options={
                'db_table': 'inventory_count_items',
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('adjustment_number', models.CharField(max_length=50, unique=True)),
                ('adjustment_quantity', models.DecimalField(decimal_places=4, help_text='Positive for increases, negative for decreases', max_digits=15)),
                ('reason', models.CharField(choices=[('count_variance', 'Physical Count Variance'), ('damage', 'Damage'), ('loss', 'Loss/Theft'), ('expiry', 'Expiry'), ('return_to_vendor', 'Return to Vendor'), ('promotion', 'Promotional Give-away'), ('sample', 'Sample'), ('correction', 'Data Correction'), ('other', 'Other')], max_length=30)),
                ('cost_impact', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Financial impact of the adjustment', max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('adjustment_date', models.DateTimeField()),
                ('approved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL)),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustments', to='core.currency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='catalog.productvariant')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.location')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.productbatch')),
            ],
            options={
                'db_table': 'inventory_adjustments',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reorder_level', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('last_counted_date', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='catalog.productvariant')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='inventory.location')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='inventory.productbatch')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment'), ('return', 'Return'), ('loss', 'Loss'), ('damage', 'Damage'), ('sale', 'Sale'), ('purchase', 'Purchase')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Positive for IN movements, negative for OUT movements', max_digits=15)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.productbatch')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'stock_movements',
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['tenant', 'is_active'], name='locations_tenant__58f9fb_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['tenant', 'location_type'], name='locations_tenant__68387e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='inventorycount',
            index=models.Index(fields=['tenant', 'location', 'status'], name='inventory_c_tenant__c8a5cf_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycount',
            index=models.Index(fields=['tenant', 'count_date'], name='inventory_c_tenant__1e4616_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycount',
            index=models.Index(fields=['tenant', 'count_number'], name='inventory_c_tenant__4a900e_idx'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['tenant', 'variant', 'is_active'], name='product_bat_tenant__50a5df_idx'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['tenant', 'batch_number'], name='product_bat_tenant__c8c219_idx'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['expiry_date'], name='product_bat_expiry__977560_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productbatch',
            unique_together={('tenant', 'variant', 'batch_number')},
        ),
        migrations.AddIndex(
            model_name='inventorycountitem',
            index=models.Index(fields=['count', 'variant'], name='inventory_c_count_i_d756c5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycountitem',
            index=models.Index(fields=['variance'], name='inventory_c_varianc_803084_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorycountitem',
            unique_together={('count', 'variant', 'batch')},
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['tenant', 'adjustment_number'], name='inventory_a_tenant__980421_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['tenant', 'variant', 'location'], name='inventory_a_tenant__9e63d2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['tenant', 'adjustment_date'], name='inventory_a_tenant__54af6a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['tenant', 'reason'], name='inventory_a_tenant__45f9ba_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['tenant', 'variant', 'location'], name='inventory_tenant__9cf57a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['tenant', 'location'], name='inventory_tenant__684c57_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['quantity_on_hand'], name='inventory_quantit_c50ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['reserved_quantity'], name='inventory_reserve_4effcf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('tenant', 'variant', 'batch', 'location')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'variant', 'location'], name='stock_movem_tenant__529cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'movement_type'], name='stock_movem_tenant__b49230_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'created_at'], name='stock_movem_tenant__6459cb_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='stock_movem_referen_a0d8b9_idx'),
        ),
    ]
