# Generated by Django 5.0.2 on 2025-06-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
