# Generated by Django 5.0.2 on 2025-06-28 15:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_productbatch_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='reorder_level',
            field=models.DecimalField(decimal_places=4, default=Decimal('10.0000'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
