# Generated by Django 5.0.2 on 2025-07-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(default='Kabul, Afghanistan', max_length=150),
            preserve_default=False,
        ),
    ]
