# Generated by Django 5.0.2 on 2025-08-03 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
