# Generated by Django 5.0.2 on 2025-08-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_productbatch_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
