# Generated by Django 5.0.2 on 2025-08-03 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_productbatch_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 2, 20, 5, 10, 103564, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
