# Generated by Django 5.0.2 on 2025-08-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_delete_attribute'),
        ('core', '0019_alter_permission_module'),
        ('inventory', '0008_alter_productbatch_expiry_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productbatch',
            name='product_bat_expiry__977560_idx',
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['tenant', 'expiry_date'], name='product_bat_tenant__cdcb39_idx'),
        ),
    ]
