# Generated by Django 5.0.2 on 2025-07-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdrawer',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
