# Generated by Django 5.0.2 on 2025-07-13 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_payment_processed_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('expense', 'Expense'), ('adjustment', 'Adjustment'), ('return', 'Return'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
