# Generated by Django 5.0.2 on 2025-07-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_address_is_default'),
        ('finance', '0004_alter_transaction_reference_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cashdrawermoney',
            name='cash_drawer_tenant__62efa5_idx',
        ),
        migrations.RemoveIndex(
            model_name='cashdrawermoney',
            name='cash_drawer_tenant__261c90_idx',
        ),
        migrations.RemoveField(
            model_name='cashdrawermoney',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='cashdrawermoney',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='cashdrawermoney',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='cashdrawermoney',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='cashdrawermoney',
            index=models.Index(fields=['cash_drawer', 'currency'], name='cash_drawer_cash_dr_8816e1_idx'),
        ),
    ]
