# Generated by Django 5.0.2 on 2025-07-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_cashdrawermoney_cash_drawer_tenant__62efa5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('expense', 'Expense'), ('salary', 'Salary'), ('dividend', 'Dividend'), ('loan', 'Loan'), ('other', 'Other'), ('customer', 'Customer'), ('vendor', 'Vendor'), ('employee', 'Employee'), ('member', 'Member')], max_length=20),
        ),
    ]
