# Generated by Django 5.0.2 on 2025-07-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_payment_reference_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_direct',
            field=models.BooleanField(default=False),
        ),
    ]
