# Generated by Django 5.0.2 on 2025-07-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_unit_unit_type'),
        ('finance', '0007_transaction_is_direct'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='monthlypayment',
            name='monthly_pay_tenant__35bf62_idx',
        ),
        migrations.RemoveIndex(
            model_name='monthlypayment',
            name='monthly_pay_tenant__d35e4e_idx',
        ),
        migrations.RemoveField(
            model_name='monthlypayment',
            name='expense_category',
        ),
        migrations.RemoveField(
            model_name='monthlypayment',
            name='vendor',
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='party_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='party_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('employee', 'Employee'), ('other', 'Other')], default='expense', max_length=20),
        ),
        migrations.AddIndex(
            model_name='monthlypayment',
            index=models.Index(fields=['tenant', 'party_type'], name='monthly_pay_tenant__169c38_idx'),
        ),
    ]
