# Generated by Django 5.0.2 on 2025-07-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_unit_unit_type'),
        ('finance', '0008_remove_monthlypayment_monthly_pay_tenant__35bf62_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='monthlypayment',
            name='monthly_pay_tenant__169c38_idx',
        ),
        migrations.RenameField(
            model_name='monthlypayment',
            old_name='party_id',
            new_name='reference_id',
        ),
        migrations.RenameField(
            model_name='monthlypayment',
            old_name='party_type',
            new_name='reference_type',
        ),
        migrations.AddIndex(
            model_name='monthlypayment',
            index=models.Index(fields=['tenant', 'reference_type'], name='monthly_pay_tenant__6444f8_idx'),
        ),
    ]
