# Generated by Django 5.0.2 on 2025-07-18 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_monthlypayment_monthly_pay_tenant__169c38_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypayment',
            name='payment_day',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
