# Generated by Django 5.0.2 on 2025-07-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_monthlypayment_payment_day'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='monthlypayment',
            name='monthly_pay_tenant__6444f8_idx',
        ),
        migrations.RemoveField(
            model_name='monthlypayment',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='monthlypayment',
            name='reference_type',
        ),
    ]
