# Generated by Django 5.0.2 on 2025-07-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_unit_unit_type'),
        ('finance', '0011_remove_monthlypayment_monthly_pay_tenant__6444f8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='reference_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('employee', 'Employee'), ('other', 'Other')], default='expense', max_length=20),
        ),
        migrations.AddIndex(
            model_name='monthlypayment',
            index=models.Index(fields=['tenant', 'reference_type'], name='monthly_pay_tenant__6444f8_idx'),
        ),
    ]
