# Generated by Django 5.0.2 on 2025-07-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_monthlypayment_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypayment',
            name='reference_type',
            field=models.CharField(choices=[('expense_category', 'Expense'), ('employee', 'Employee'), ('other', 'Other')], default='expense', max_length=20),
        ),
    ]
