# Generated by Django 5.0.2 on 2025-07-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_monthlypayment_reference_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('expense', 'Expense'), ('salary', 'Salary'), ('dividend', 'Dividend'), ('loan', 'Loan'), ('other', 'Other'), ('customer', 'Customer'), ('vendor', 'Vendor'), ('employee', 'Employee'), ('member', 'Member'), ('customer_statement', 'Customer Statement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('expense', 'Expense'), ('adjustment', 'Adjustment'), ('return', 'Return'), ('customer_statement', 'Customer Statement'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
