# Generated by Django 5.0.2 on 2025-07-20 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_payment_reference_type_and_more'),
        ('inventory', '0005_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdrawer',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_drawer', to='inventory.location'),
        ),
    ]
