# Generated by Django 5.0.2 on 2025-07-20 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_cashdrawer_location'),
        ('inventory', '0005_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdrawer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_drawers', to='inventory.location'),
        ),
    ]
