# Generated by Django 5.0.2 on 2025-07-29 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_cashdrawer_location'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expensecategory',
            name='expense_cat_tenant__3db40f_idx',
        ),
    ]
