# Generated by Django 5.0.2 on 2025-07-29 22:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_tenantsettings_tenant_sett_tenant__e0b783_idx'),
        ('finance', '0017_remove_expensecategory_expense_cat_tenant__3db40f_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_tenant__1bdc3b_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_tenant__4e424f_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_expense_003f04_idx',
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('tenant', 'expense_number')},
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_number',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='expense',
            name='approved_by_user',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='receipt_reference',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='status',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vendor',
        ),
    ]
