# Generated by Django 5.0.2 on 2025-07-29 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_remove_expense_expenses_tenant__1bdc3b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cash_drawer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paid_expenses', to='finance.cashdrawer'),
            preserve_default=False,
        ),
    ]
