# Generated by Django 5.0.2 on 2025-07-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_expense_cash_drawer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
