# Generated by Django 5.0.2 on 2025-07-29 22:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_alter_expense_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
