# Generated by Django 5.0.2 on 2025-06-24 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('is_loved', models.BooleanField(default=False)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_product_preferences',
                'indexes': [models.Index(fields=['tenant', 'user', 'is_favorite'], name='user_produc_tenant__a9d7da_idx'), models.Index(fields=['tenant', 'user', 'is_bookmarked'], name='user_produc_tenant__0ccd9a_idx'), models.Index(fields=['last_viewed_at'], name='user_produc_last_vi_685e3e_idx'), models.Index(fields=['view_count'], name='user_produc_view_co_876682_idx')],
                'unique_together': {('user', 'product', 'tenant')},
            },
        ),
    ]
