# Generated by Django 5.0.2 on 2025-07-11 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_managers_and_more'),
        ('catalog', '0023_rename_reference_id_barcodes_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userproductpreference',
            name='user_produc_last_vi_685e3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='userproductpreference',
            name='user_produc_view_co_876682_idx',
        ),
        migrations.RemoveField(
            model_name='userproductpreference',
            name='last_viewed_at',
        ),
        migrations.RemoveField(
            model_name='userproductpreference',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='userproductpreference',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='userproductpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
