# Generated by Django 5.0.2 on 2025-07-11 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userproductpreference_user_produc_last_vi_685e3e_idx_and_more'),
        ('catalog', '0023_rename_reference_id_barcodes_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductpreference',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='userproductpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
