# Generated by Django 5.0.2 on 2025-07-12 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userproductpreference_product_and_more'),
        ('catalog', '0023_rename_reference_id_barcodes_object_id_and_more'),
        ('core', '0005_alter_address_addressable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductpreference',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='catalog.productvariant'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userproductpreference',
            unique_together={('user', 'variant', 'tenant')},
        ),
        
        migrations.AddIndex(
            model_name='userproductpreference',
            index=models.Index(fields=['tenant', 'user', 'is_loved'], name='user_produc_tenant__2991c2_idx'),
        ),
        migrations.RemoveField(
            model_name='userproductpreference',
            name='product',
        ),
    ]
