# Generated by Django 5.0.2 on 2025-07-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userproductpreference_unique_together_and_more'),
        ('core', '0011_alter_unit_unit_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_employe_68f2c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_name_dfe7fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_hire_da_c03eea_idx',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_number',
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'name'], name='employees_tenant__a4e450_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'hire_date'], name='employees_tenant__cc6c98_idx'),
        ),
    ]
