# Generated by Django 5.0.2 on 2025-07-26 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_employee_email_alter_employee_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('da', 'Dari'), ('pa', 'Pashto'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
