# Generated by Django 5.0.2 on 2025-07-26 08:15

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_language_preference_alter_userrole_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='User profile photo', null=True, upload_to=accounts.utils.upload_user_photo),
        ),
    ]
