# Generated by Django 5.0.2 on 2025-07-26 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_photo'),
        ('inventory', '0005_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='inventory.location'),
            preserve_default=False,
        ),
    ]
