# Generated by Django 5.0.2 on 2025-07-26 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_location'),
        ('core', '0014_remove_tenantsettings_tenant_sett_tenant__e0b783_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userrole',
            name='user_roles_tenant__244d6d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('tenant', 'role_name')},
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_roles', to='accounts.userrole'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='light', max_length=20),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['tenant', 'is_active'], name='user_roles_tenant__2acc38_idx'),
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
    ]
