# Generated by Django 5.0.2 on 2025-07-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_role'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userrole',
            name='user_roles_tenant__7b3b0a_idx',
        ),
        migrations.RemoveIndex(
            model_name='userrole',
            name='user_roles_assigne_ef5382_idx',
        ),
        migrations.RemoveIndex(
            model_name='userrole',
            name='user_roles_tenant__2acc38_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role_name',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('manager', 'Manager'), ('employee', 'Employee'), ('cashier', 'Cashier'), ('inventory_manager', 'Inventory Manager'), ('sales_rep', 'Sales Representative'), ('accountant', 'Accountant'), ('viewer', 'Viewer'), ('custom', 'Custom')], max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='assigned_date',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='updated_at',
        ),
    ]
