# Generated by Django 5.0.2 on 2025-08-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_userrole_user_roles_tenant__7b3b0a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('employee', 'Employee'), ('cashier', 'Cashier'), ('inventory_manager', 'Inventory Manager'), ('sales_rep', 'Sales Representative'), ('accountant', 'Accountant'), ('viewer', 'Viewer')], default='admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('employee', 'Employee'), ('cashier', 'Cashier'), ('inventory_manager', 'Inventory Manager'), ('sales_rep', 'Sales Representative'), ('accountant', 'Accountant'), ('viewer', 'Viewer')], max_length=50),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
