# Generated by Django 5.0.2 on 2025-08-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_user_role_user_role_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_tenant__2f74ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_tenant__502e59_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_tenant__afadfd_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_last_lo_baae4d_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_date',
        ),
    ]
