# Generated by Django 5.0.2 on 2025-06-24 13:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(choices=[('users', 'Users'), ('products', 'Products'), ('inventory', 'Inventory'), ('sales', 'Sales'), ('purchases', 'Purchases'), ('customers', 'Customers'), ('vendors', 'Vendors'), ('finance', 'Finance'), ('reports', 'Reports'), ('settings', 'Settings')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'permissions',
                'indexes': [models.Index(fields=['module'], name='permissions_module_2c0512_idx')],
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('business_type', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('manufacturing', 'Manufacturing'), ('service', 'Service'), ('restaurant', 'Restaurant'), ('other', 'Other')], default='retail', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('trial', 'Trial')], default='trial', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_plan', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('max_users', models.PositiveIntegerField(default=5)),
                ('max_products', models.PositiveIntegerField(default=1000)),
                ('max_locations', models.PositiveIntegerField(default=1)),
                ('max_storage_mb', models.PositiveIntegerField(default=1024)),
            ],
            options={
                'db_table': 'tenants',
                'indexes': [models.Index(fields=['domain'], name='tenants_domain_726e44_idx'), models.Index(fields=['status'], name='tenants_status_80d9b6_idx'), models.Index(fields=['contact_email'], name='tenants_contact_f5cb2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
                ('symbol', models.CharField(max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(4)])),
                ('is_base_currency', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'db_table': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('addressable_type', models.CharField(max_length=50)),
                ('addressable_id', models.PositiveIntegerField()),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping'), ('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=20)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout')], max_length=20)),
                ('table_name', models.CharField(blank=True, max_length=100)),
                ('record_id', models.PositiveIntegerField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=40)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'activity_logs',
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('setting_key', models.CharField(max_length=100)),
                ('setting_value', models.TextField()),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'tenant_settings',
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('plan_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('trialing', 'Trialing')], default='active', max_length=20)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('invoice', 'Invoice'), ('cash', 'Cash')], default='credit_card', max_length=20)),
                ('next_billing_date', models.DateTimeField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'tenant_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20)),
                ('unit_type', models.CharField(choices=[('weight', 'Weight'), ('volume', 'Volume'), ('length', 'Length'), ('area', 'Area'), ('count', 'Count'), ('time', 'Time')], max_length=20)),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=1.0, max_digits=15)),
                ('is_base_unit', models.BooleanField(default=False)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_units', to='core.unit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'units',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('setting_key', models.CharField(max_length=100)),
                ('setting_value', models.TextField()),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('security', 'Security'), ('notifications', 'Notifications'), ('integration', 'Integration'), ('billing', 'Billing')], default='general', max_length=20)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'system_settings',
                'indexes': [models.Index(fields=['tenant', 'category'], name='system_sett_tenant__01f9f3_idx'), models.Index(fields=['tenant', 'setting_key'], name='system_sett_tenant__e19218_idx')],
                'unique_together': {('tenant', 'setting_key')},
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15, validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.currency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'currency_rates',
                'indexes': [models.Index(fields=['tenant', 'currency', 'effective_date'], name='currency_ra_tenant__342eb1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['tenant', 'is_base_currency'], name='currencies_tenant__a6e325_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['tenant', 'is_active'], name='currencies_tenant__99db78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['tenant', 'addressable_type', 'addressable_id'], name='addresses_tenant__6a27ed_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['tenant', 'address_type'], name='addresses_tenant__a04ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['tenant', 'user', 'timestamp'], name='activity_lo_tenant__10a75a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['tenant', 'action', 'timestamp'], name='activity_lo_tenant__37b888_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['tenant', 'table_name', 'timestamp'], name='activity_lo_tenant__49da8e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantsettings',
            index=models.Index(fields=['tenant', 'setting_key'], name='tenant_sett_tenant__89f82e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantsettings',
            unique_together={('tenant', 'setting_key')},
        ),
        migrations.AddIndex(
            model_name='tenantsubscription',
            index=models.Index(fields=['tenant', 'status'], name='tenant_subs_tenant__11bdb5_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantsubscription',
            index=models.Index(fields=['next_billing_date'], name='tenant_subs_next_bi_55bda3_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['tenant', 'unit_type'], name='units_tenant__aede15_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['tenant', 'is_base_unit'], name='units_tenant__3b9be8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('tenant', 'name')},
        ),
    ]
