# Generated by Django 5.0.2 on 2025-06-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('security', 'Security'), ('notifications', 'Notifications'), ('integration', 'Integration'), ('billing', 'Billing')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='max_locations',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddIndex(
            model_name='tenantsettings',
            index=models.Index(fields=['tenant', 'category'], name='tenant_sett_tenant__e0b783_idx'),
        ),
    ]
