# Generated by Django 5.0.2 on 2025-06-26 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_alter_currency_symbol'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='address',
            new_name='addresses_tenant__97151e_idx',
            old_name='addresses_tenant__6a27ed_idx',
        ),
        migrations.AlterField(
            model_name='address',
            name='addressable_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='contenttypes.contenttype'),
        ),
    ]
