# Generated by Django 5.0.2 on 2025-06-26 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_rename_addresses_tenant__6a27ed_idx_addresses_tenant__97151e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressable_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
