# Generated by Django 5.0.2 on 2025-07-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_unit_unit_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]
