# Generated by Django 5.0.2 on 2025-07-23 17:33

import core.image_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='setting_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.image_path.settings_image_upload_path),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='setting_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON'), ('image', 'Image')], default='string', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='setting_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
