# Generated by Django 5.0.2 on 2025-07-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tenantsettings_setting_image_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tenantsettings',
            name='tenant_sett_tenant__e0b783_idx',
        ),
    ]
