# Generated by Django 5.0.2 on 2025-07-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_tenantsettings_tenant_sett_tenant__e0b783_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('users', 'Users'), ('products', 'Products'), ('inventory', 'Inventory'), ('sales', 'Sales'), ('purchases', 'Purchases'), ('customers', 'Customers'), ('vendors', 'Vendors'), ('finance', 'Finance'), ('reports', 'Reports'), ('settings', 'Settings'), ('product_details', 'Product Details'), ('expense', 'Expense'), ('memebers', 'Members'), ('employees', 'Employees'), ('stock_and_warehouse', 'Stock and Warehouse'), ('currency', 'Currency'), ('units', 'Units')], max_length=50),
        ),
    ]
