# Generated by Django 5.0.2 on 2025-08-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_permission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('users', 'Users'), ('inventory', 'Inventory'), ('sales', 'Sales'), ('purchases', 'Purchases'), ('customers', 'Customers'), ('finance', 'Finance'), ('reports', 'Reports'), ('settings', 'Settings'), ('product_details', 'Product Details'), ('expense', 'Expense'), ('stock_and_warehouse', 'Stock and Warehouse'), ('currency', 'Currency'), ('units', 'Units'), ('discount', 'Discount')], max_length=50),
        ),
    ]
