# Generated by Django 5.0.2 on 2025-07-15 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_location_address'),
        ('sales', '0003_alter_sales_status_alter_sales_subtotal'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='saleitem',
            name='sale_items_variant_6c753a_idx',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='location',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.inventory'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['inventory'], name='sale_items_invento_3d937b_idx'),
        ),
    ]
