# Generated by Django 5.0.2 on 2025-07-15 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_address_is_default'),
        ('customers', '0004_customer_address'),
        ('sales', '0004_remove_saleitem_sale_items_variant_6c753a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sales',
            name='sales_sale_nu_ee8c51_idx',
        ),
        migrations.AddField(
            model_name='sales',
            name='receipt_id',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='sales',
            unique_together={('tenant', 'receipt_id'), ('tenant', 'sale_number')},
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['tenant', 'receipt_id'], name='sales_tenant__50a291_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['tenant', 'sale_number'], name='sales_tenant__46b0ea_idx'),
        ),
    ]
