# Generated by Django 5.0.2 on 2025-07-16 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '000X_move_barcodes_to_productvariant'),
        ('core', '0008_alter_address_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'sku'), ('product', 'variant_name'), ('tenant', 'barcode')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['tenant', 'barcode'], name='product_var_tenant__199ff8_idx'),
        ),
    ]
