# Generated by Django 5.0.2 on 2025-06-24 18:33

import catalog.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_type', models.CharField(choices=[('variant', 'Product Variant'), ('batch', 'Product Batch')], default='variant', max_length=20)),
                ('reference_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_tenant__67a8c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='product_var_barcode_9fdfa1_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_currency',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='barcode',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_variants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variant_prices', to='catalog.productvariant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image', null=True, upload_to=catalog.utils.product_image_path),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='barcodes',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
    ]
