# Generated by Django 5.0.2 on 2025-07-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
