# Generated by Django 5.0.2 on 2025-06-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_barcodes_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Apple', max_length=200),
            preserve_default=False,
        ),
    ]
