# Generated by Django 5.0.2 on 2025-08-03 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productvariant_barcode'),
        ('core', '0019_alter_permission_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_tenant__76cb13_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_tenant__fc2a65_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_tenant__73086f_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_created_e1ba5f_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'category'], name='products_tenant__960dbe_idx'),
        ),
    ]
