# Generated by Django 5.0.2 on 2025-06-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodes',
            name='barcode',
            field=models.CharField(default='01', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
