# Generated by Django 5.0.2 on 2025-08-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_products_tenant__76cb13_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariantAttribute',
        ),
    ]
