# Generated by Django 5.0.2 on 2025-08-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_delete_productvariantattribute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttributeValue',
        ),
    ]
