# Generated by Django 5.0.2 on 2025-06-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_barcodes_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodes',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='barcodes',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='barcodes',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='barcodes',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
