# Generated by Django 5.0.2 on 2025-08-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_delete_attributevalue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
