# Generated by Django 5.0.2 on 2025-06-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_reorder_level'),
        ('core', '0003_alter_currency_symbol'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'name')},
        ),
    ]
