# Generated by Django 5.0.2 on 2025-06-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'variant_name')},
        ),
    ]
