# Generated by Django 5.0.2 on 2025-06-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_productvariant_variant_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productvariant',
            name='product_var_sku_3a95f0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'sku'), ('product', 'variant_name')},
        ),
    ]
