# Generated by Django 5.0.2 on 2025-06-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_productvariant_product_var_sku_3a95f0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=100),
        ),
    ]
