# Generated by Django 5.0.2 on 2025-06-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barcodes',
            table='barcodes',
        ),
    ]
