# Generated by Django 5.0.2 on 2025-06-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_barcodes_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variant_name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
