# Generated by Django 5.0.2 on 2025-06-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_productvariant_variant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
