# Generated by Django 5.0.2 on 2025-06-26 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_productvariant_variant_name'),
        ('core', '0003_alter_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productprice',
            name='effective_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
