# Generated by Django 5.0.2 on 2025-06-28 14:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_productvariant_sku'),
        ('core', '0005_alter_address_addressable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barcodes',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='barcodes',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barcodes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='barcodes',
            name='barcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='barcodes',
            unique_together={('tenant', 'barcode')},
        ),
    ]
