# Generated by Django 5.0.2 on 2025-06-28 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_barcodes_created_at_barcodes_deleted_at_and_more'),
        ('core', '0005_alter_address_addressable_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodes',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='core.tenant'),
        ),
    ]
