# Generated by Django 5.0.2 on 2025-06-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_barcodes_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodes',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='barcodes',
            name='updated_at',
        ),
    ]
