# Generated by Django 5.0.2 on 2025-06-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_remove_barcodes_deleted_at_and_more'),
        ('core', '0005_alter_address_addressable_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barcodes',
            unique_together={('tenant', 'barcode', 'reference_id')},
        ),
    ]
