# Generated by Django 5.0.2 on 2025-06-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_barcodes_unique_together'),
        ('core', '0005_alter_address_addressable_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barcodes',
            unique_together={('tenant', 'barcode'), ('tenant', 'reference_id')},
        ),
    ]
