# Generated by Django 5.0.2 on 2025-07-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_barcodes_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='cost_currency',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='selling_currency',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='selling_price',
        ),
    ]
