# Generated by Django 5.0.2 on 2025-07-09 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_remove_productvariant_cost_currency_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_alter_address_addressable_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcodes',
            old_name='reference_id',
            new_name='object_id',
        ),
        migrations.AlterUniqueTogether(
            name='barcodes',
            unique_together={('tenant', 'barcode'), ('tenant', 'object_id')},
        ),
        migrations.AddField(
            model_name='barcodes',
            name='content_type',
            field=models.ForeignKey(default=26, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='barcodes',
            name='reference_type',
        ),
    ]
