# Generated by Django 5.0.2 on 2025-07-13 20:36

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_address_is_default'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='preferred_currency',
            field=models.ForeignKey(blank=True, default=core.models.Currency.get_base_currency, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_customers', to='core.currency'),
        ),
    ]
