# Generated by Django 5.0.2 on 2025-07-13 20:58

import customers.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_preferred_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customernote',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='customernote',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customernote',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='anniversary_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='preferred_payment_method',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='referral_source',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='website',
        ),
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, help_text='Customer image', null=True, upload_to=customers.utils.customer_image_path),
        ),
        migrations.DeleteModel(
            name='CustomerContact',
        ),
        migrations.DeleteModel(
            name='CustomerNote',
        ),
    ]
