# Generated by Django 5.0.2 on 2025-07-15 22:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=9, default=Decimal('0.00'), max_digits=15),
        ),
    ]
