# Generated by Django 5.0.2 on 2025-07-19 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_unit_unit_type'),
        ('customers', '0007_customerstatement'),
        ('finance', '0013_alter_monthlypayment_reference_type'),
        ('sales', '0007_alter_sales_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customerstatement',
            name='customer_st_tenant__f8ebf4_idx',
        ),
        migrations.RenameField(
            model_name='customerstatement',
            old_name='sale_id',
            new_name='sale',
        ),
        migrations.AddIndex(
            model_name='customerstatement',
            index=models.Index(fields=['tenant', 'sale'], name='customer_st_tenant__fab2ec_idx'),
        ),
    ]
