# Generated by Django 5.0.2 on 2025-07-19 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_remove_customerstatement_customer_st_tenant__f8ebf4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstatement',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='customers.customer'),
        ),
    ]
