# Generated by Django 5.0.2 on 2025-07-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_customerstatement_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerstatement',
            options={'ordering': ['-statement_date']},
        ),
    ]
