# Generated by Django 5.0.2 on 2025-07-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_tenantsettings_tenant_sett_tenant__e0b783_idx'),
        ('customers', '0011_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('tenant', 'customer_number'), ('tenant', 'email')},
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('tenant', 'customer_number'), ('tenant', 'email'), ('tenant', 'name')},
        ),
    ]
