# Generated by Django 5.0.2 on 2025-07-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_customer_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_tenant__074712_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_tenant__a2831a_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_tenant__9b9837_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_tenant__515774_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_tenant__bac0f9_idx',
        ),
    ]
