# Generated by Django 5.0.2 on 2025-08-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_remove_customer_customers_tenant__074712_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='credit_limit',
        ),
    ]
