# Generated by Django 5.0.2 on 2025-08-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_remove_customer_credit_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sales_rep',
        ),
    ]
