# Generated by Django 5.0.2 on 2025-08-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_remove_customer_sales_rep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='groups',
        ),
        migrations.DeleteModel(
            name='CustomerGroupMembership',
        ),
    ]
