# Generated by Django 5.0.2 on 2025-08-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_remove_customer_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerGroup',
        ),
    ]
